[package]
name = "jcfg"
description = "A library for serializing jcfg files."
license = "MIT"
version = "0.1.3"
edition = "2021"
repository = "https://github.com/enzious/jcfg"

[dependencies]
indent = "0.1.1"
serde = "1.0.203"
serde_derive = "1.0.203"
